# Generated by Django 4.2.11 on 2024-04-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('orgs', '0004_alter_organization_update_date'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='organization_location',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='area_of_interest',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_available',
            field=models.ManyToManyField(blank=True, related_name='user_available_skills', to='skills.skill', verbose_name='Available skills'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='affiliation',
            field=models.ManyToManyField(blank=True, related_name='user_affiliation', to='orgs.organization', verbose_name='Affiliation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills_known',
            field=models.ManyToManyField(blank=True, related_name='user_known_skils', to='skills.skill', verbose_name='Skill known'),
        ),
        migrations.DeleteModel(
            name='AreaOfInterest',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationType',
        ),
    ]
