# Generated by Django 4.2.7 on 2023-11-09 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 14, 44, 49, 67947), verbose_name='date joined'),
        ),
    ]
