# Generated by Django 4.2.7 on 2023-11-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='About me'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='profile',
            name='irc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='IRC'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wiki_develop',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Wikimedia developer account'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wiki_unified',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Wikimedia user account'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('wiki', 'Discussion page'), ('wiki', 'Meta-Wiki talk page'), ('telegram', 'Telegram'), ('IRC', 'IRC')], max_length=10, null=True, verbose_name='Preferred contact method'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Twitter'),
        ),
    ]
