# Generated by Django 4.2.11 on 2024-04-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('users', '0003_alter_profile_contact_method_and_more'), ('users', '0004_alter_profile_about')]

    dependencies = [
        ('users', '0002_remove_organization_organization_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('discussion', 'Discussion page'), ('wiki', 'Meta-Wiki talk page'), ('telegram', 'Telegram'), ('IRC', 'IRC')], default='', max_length=10, verbose_name='Preferred contact method'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=387, verbose_name='Display name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Facebook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='GitHub'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Instagram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='irc',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='IRC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='pronoun',
            field=models.CharField(blank=True, choices=[('he-him', 'He/Him'), ('she-her', 'She/Her'), ('they-them', 'They/Them')], default='', max_length=20, verbose_name='Pronoun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Telegram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Twitter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='wiki_alt',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Wikimedia alternative account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='wiki_develop',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Wikimedia developer account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='About me'),
        ),
    ]
