# Generated by Django 5.0 on 2023-12-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_about_profile_github_profile_irc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_description_af',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ar',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ar_dz',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ast',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_az',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_be',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_bg',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_bn',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_br',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_bs',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ca',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ckb',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_cs',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_cy',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_da',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_de',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_dsb',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_el',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_en_au',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_en_gb',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_eo',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_es_ar',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_es_co',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_es_mx',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_es_ni',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_es_ve',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_et',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_eu',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_fa',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_fi',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_fr',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_fy',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ga',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_gd',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_gl',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_he',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_hi',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_hr',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_hsb',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_hu',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_hy',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ia',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ig',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ind',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_io',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_is',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_it',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ja',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ka',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_kab',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_kk',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_km',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_kn',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ko',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ky',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_lb',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_lt',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_lv',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_mk',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ml',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_mn',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_mr',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ms',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_my',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_nb',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ne',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_nl',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_nn',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_os',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_pa',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_pl',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ro',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ru',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_sk',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_sl',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_sq',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_sr',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_sr_latn',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_sv',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_sw',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ta',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_te',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_tg',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_th',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_tk',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_tr',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_tt',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_udm',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ug',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_uk',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_ur',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_uz',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_vi',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_zh_hans',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description_zh_hant',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_af',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ar',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ar_dz',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ast',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_az',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_be',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_bg',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_bn',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_br',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_bs',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ca',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ckb',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_cs',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_cy',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_da',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_de',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_dsb',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_el',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_en_au',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_en_gb',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_eo',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_es_ar',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_es_co',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_es_mx',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_es_ni',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_es_ve',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_et',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_eu',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_fa',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_fi',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_fr',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_fy',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ga',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_gd',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_gl',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_he',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_hi',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_hr',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_hsb',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_hu',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_hy',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ia',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ig',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ind',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_io',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_is',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_it',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ja',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ka',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_kab',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_kk',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_km',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_kn',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ko',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ky',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_lb',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_lt',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_lv',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_mk',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ml',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_mn',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_mr',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ms',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_my',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_nb',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ne',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_nl',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_nn',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_os',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_pa',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_pl',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ro',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ru',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_sk',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_sl',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_sq',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_sr',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_sr_latn',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_sv',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_sw',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ta',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_te',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_tg',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_th',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_tk',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_tr',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_tt',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_udm',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ug',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_uk',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ur',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_uz',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_vi',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_zh_hans',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_zh_hant',
            field=models.CharField(error_messages={'unique': "There's another organization with that name."}, max_length=256, null=True, unique=True, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_af',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ar',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ar_dz',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ast',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_az',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_be',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_bg',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_bn',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_br',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_bs',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ca',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ckb',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_cs',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_cy',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_da',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_de',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_dsb',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_el',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_en_au',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_en_gb',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_eo',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_es_ar',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_es_co',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_es_mx',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_es_ni',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_es_ve',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_et',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_eu',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_fa',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_fi',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_fr',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_fy',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ga',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_gd',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_gl',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_he',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_hi',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_hr',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_hsb',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_hu',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_hy',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ia',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ig',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ind',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_io',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_is',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_it',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ja',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ka',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_kab',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_kk',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_km',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_kn',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ko',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ky',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_lb',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_lt',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_lv',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_mk',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ml',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_mn',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_mr',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ms',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_my',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_nb',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ne',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_nl',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_nn',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_os',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_pa',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_pl',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ro',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ru',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_sk',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_sl',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_sq',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_sr',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_sr_latn',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_sv',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_sw',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ta',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_te',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_tg',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_th',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_tk',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_tr',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_tt',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_udm',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ug',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_uk',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_ur',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_uz',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_vi',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_zh_hans',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_name_zh_hant',
            field=models.CharField(max_length=140, null=True, verbose_name='Type name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_code',
            field=models.CharField(error_messages={'unique': "There's another organization with that code."}, max_length=20, unique=True, verbose_name='Organization code'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_description_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_description_es',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_description_pt',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_description_pt_br',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Organization description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_website',
            field=models.URLField(blank=True, error_messages={'unique': 'This website is already used by another organization.'}, null=True, unique=True, verbose_name='Organization website'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('discussion', 'Discussion page'), ('wiki', 'Meta-Wiki talk page'), ('telegram', 'Telegram'), ('IRC', 'IRC')], max_length=10, null=True, verbose_name='Preferred contact method'),
        ),
    ]
