# Generated by Django 4.2.7 on 2023-11-14 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_about_profile_github_profile_wiki_develop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 15, 54, 16, 281793), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='About me'),
        ),
    ]
