# Generated by Django 4.2.7 on 2024-02-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_organization_organization_description_af_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wiki_unified',
        ),
        migrations.AddField(
            model_name='profile',
            name='wiki_alt',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Wikimedia alternative account'),
        ),
    ]
