# Generated by Django 4.2.9 on 2024-04-17 16:54

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('users', '0005_territory_remove_profile_region_profile_wikidata_qid_and_more'), ('users', '0006_alter_profile_wikidata_qid_and_more')]

    dependencies = [
        ('orgs', '0004_remove_organization_social_media_and_more'),
        ('users', '0004_remove_social_medias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Region',
            new_name='Territory',
        ),
        migrations.RenameField(
            model_name='territory',
            old_name='region_name',
            new_name='territory_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='region',
            new_name='territory',
        ),
        migrations.AlterField(
            model_name='profile',
            name='territory',
            field=models.ManyToManyField(blank=True, related_name='user_territory', to='users.territory', verbose_name='Territory'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='parent_region',
            field=models.ManyToManyField(blank=True, related_name='territory_parent', to='users.territory', verbose_name='Parent territory'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='territory_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Territory name'),
        ),
    ]
