# Generated by Django 4.2.7 on 2023-11-14 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_date_joined_alter_profile_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.AddField(
            model_name='profile',
            name='irc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='IRC'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 15, 59, 5, 534208), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Twitter'),
        ),
    ]
