# Generated by Django 4.2.9 on 2024-04-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_region_to_territory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='territory',
            old_name='parent_region',
            new_name='parent_territory',
        ),
    ]
