# Generated by Django 4.2.11 on 2024-05-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_field-revision'),
    ]

    operations = [
    ]
