# Generated by Django 4.2.11 on 2024-05-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.JSONField(blank=True, help_text='json', null=True, verbose_name='Contact methods'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social',
            field=models.JSONField(blank=True, help_text='json', null=True, verbose_name='Social medias'),
        ),
    ]
