# Generated by Django 4.2.11 on 2024-06-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_is_active_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language_autonym',
            field=models.CharField(blank=True, max_length=128, verbose_name='Language autonym'),
        ),
    ]
