# Generated by Django 4.2.6 on 2024-03-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_of_creation', models.DateField()),
                ('date_of_last_edit', models.DateField()),
                ('description', models.CharField(max_length=512)),
                ('wiki_link', models.URLField(max_length=256)),
                ('in_person_event', models.BooleanField()),
                ('country', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
