# Generated by Django 4.2.11 on 2024-07-30 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0005_alter_organization_territory'),
        ('events', '0002_add_eventparticipant_eventorganizations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizations',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='Event Creator'),
        ),
    ]
