# Generated by Django 4.2.11 on 2024-04-10 14:33

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('orgs', '0001_initial'), ('orgs', '0002_alter_organization_contact_and_more')]

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('profile_image', models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Invalid URL format. The format should be https://commons.wikimedia.org/wiki/File:filename.ext', regex='^https:\\/\\/commons\\.wikimedia\\.org\\/wiki\\/File:.*?\\.[\\w]+$')])),
                ('acronym', models.CharField(max_length=10, unique=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('social_media', models.URLField(blank=True, null=True)),
                ('home_project', models.URLField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('territory', models.ManyToManyField(to='users.region')),
            ],
        ),
    ]
