# Generated by Django 4.2.11 on 2024-04-11 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('orgs', '0002_remove_organization_contact_organization_managers'), ('orgs', '0003_organizationtype_remove_organization_creation_date_and_more'), ('orgs', '0004_alter_organization_update_date')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0001_initials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contact',
        ),
        migrations.AddField(
            model_name='organization',
            name='managers',
            field=models.ManyToManyField(related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=20, unique=True)),
                ('type_name', models.CharField(max_length=140)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.RESTRICT, to='orgs.organizationtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
