# Generated by Django 4.2.11 on 2024-04-12 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_alter_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='social_media',
        ),
        migrations.AddField(
            model_name='organization',
            name='meta_page',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Invalid URL format. The format should be https://meta.wikimedia.org/wiki/PageName', regex='^https:\\/\\/meta\\.wikimedia\\.org\\/wiki\\/.*?$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='home_project',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Invalid URL format. The format should be https://xx.wikimedia.org/', regex='^https:\\/\\/[\\w-]+\\.wikimedia\\.org\\/$')]),
        ),
    ]
