# Generated by Django 4.2.9 on 2024-04-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_territory_remove_profile_region_profile_wikidata_qid_and_more'),
        ('orgs', '0004_remove_organization_social_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='territory',
            field=models.ManyToManyField(blank=True, related_name='territory', to='users.territory'),
        ),
    ]
