# Generated by Django 4.2.6 on 2024-03-01 20:35

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=128, verbose_name='Name')),
                ('skill_description', models.CharField(max_length=1000, verbose_name='Description')),
                ('skill_wikidata_item', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Field must be in the format "Q123456789"', regex='^Q\\d+$')], verbose_name='Wikidata item associated')),
                ('skill_date_of_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('skill_type', models.ManyToManyField(blank=True, to='skills.skill', verbose_name='Skill type')),
            ],
        ),
    ]
