# Generated by Django 4.2.9 on 2024-04-17 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_wikidata_item',
            field=models.CharField(blank=True, default='', max_length=30, validators=[django.core.validators.RegexValidator(message='Field must be in the format "Q123456789"', regex='^Q\\d+$')], verbose_name='Wikidata item associated'),
        ),
    ]
