# Generated by Django 4.2.7 on 2023-11-14 22:19

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=128, verbose_name='Name')),
                ('service_description', models.TextField(max_length=1000, verbose_name='Description')),
                ('service_wikidata_item', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Field must be in the format "Q123456789"', regex='^Q\\d+$')], verbose_name='Wikidata item associated')),
                ('service_date_of_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_type', models.ManyToManyField(blank=True, to='skills.service', verbose_name='Service type'),),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='date_of_creation',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='date_of_last_edit',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='family',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='profile_header',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='self_learning',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='wiki_link',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_date_of_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_description',
            field=models.CharField(default='', max_length=1000, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(default='', max_length=128, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.ManyToManyField(blank=True, to='skills.skill', verbose_name='Skill type')
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_wikidata_item',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Field must be in the format "Q123456789"', regex='^Q\\d+$')], verbose_name='Wikidata item associated'),
        ),
        migrations.DeleteModel(
            name='Skill_Family',
        ),
    ]
