# Generated by Django 4.2.11 on 2024-05-20 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_skill_wikidata_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_name',
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_wikidata_item',
            field=models.CharField(default='', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Field must be in the format "Q123456789"', regex='^Q\\d+$')], verbose_name='Wikidata item associated'),
        ),
    ]
