# Generated by Django 5.0 on 2024-01-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(choices=[('error', 'Error'), ('new_feature', 'New Feature'), ('improvement', 'Improvement'), ('test_case', 'Test Case')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('done', 'Done')], max_length=20),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bugs.bug')),
            ],
        ),
    ]
