# Generated by Django 5.0 on 2024-02-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_alter_bug_bug_type_alter_bug_status_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(blank=True, choices=[('error', 'Error'), ('new_feature', 'New Feature'), ('improvement', 'Improvement'), ('test_case', 'Test Case')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(blank=True, choices=[('to_do', 'To Do'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('done', 'Done')], max_length=20, null=True),
        ),
    ]
